name: CI-CD 

on:
  # push:
  #   branches: ["main"]
  workflow_dispatch:
jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Source code checkout
        uses: actions/checkout@v4
      - name: Dockerhub authentication
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push Docker image 
        uses: docker/build-push-action@v6
        with:
          context: ./src
          file: ./src/Dockerfile
          push: true
          tags: |
            raphaelmb/fake-shop:v${{ github.run_number }}
            raphaelmb/fake-shop:latest

  cd:
    needs: [ci]
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
      actions: read
    steps:
      - name: Source code checkout
        uses: actions/checkout@v4
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      - name: Configure kubectl
        run: aws eks update-kubeconfig --name aula-k8s
      - name: Apply k8s manifestos
        uses: Azure/k8s-deploy@v5
        with:
          manifests: |
            ./k8s/deployment.yaml
          images: |
            raphaelmb/fake-shop:v${{ github.run_number }}
