name: CI-CD 

on:
  push:
    branches: ["main"]
  workflow_dispatch:
jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Source code checkout
        uses: actions/checkout@v4
      - name: Dockerhub authentication
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push Docker image 
        uses: docker/build-push-action@v6
        with:
          context: ./src
          file: ./src/Dockerfile
          push: true
          tags: |
            raphaelmb/fake-shop:v${{ github.run_number }}
            raphaelmb/fake-shop:latest
  #
  # cd:
  #   needs: [ci]
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: AWS authentication
  #       run: ""
  #     - name: Kubectl configuration
  #       run: ""
  #     - name: Apply k8s manifestos
  #       run: ""
