name: CI-CD 

on:
  push:
    branches: ["main"]
  workflow_dispatch:
jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Source code checkout
        uses: actions/checkout@v4
      - name: Dockerhub authentication
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
  #     - name: Build Docker image 
  #       run: ""
  #     - name: Push Docker image
  #       run: ""
  #
  # cd:
  #   needs: [ci]
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: AWS authentication
  #       run: ""
  #     - name: Kubectl configuration
  #       run: ""
  #     - name: Apply k8s manifestos
  #       run: ""
